### PR TITLE
Exclude WooCommerce + Translation

### PR DESCRIPTION
**Pull request by gablau**
* exclude cache for WooCommerce
* fix load textdomain
* add Italian (it_IT) translation

### CODE REVIEW

**Comment by Tobias-Conrad** [comment]
https://docs.woothemes.com/document/configuring-caching-plugins/
Excluding pages from the cache ↑ Back to Top
If using caching plugins (such as WP Super Cache or W3 Total Cache), make sure you exclude the following pages from the cache through their respective settings panels:

Cart
My Account
Checkout
These pages need to stay dynamic since they display information specific to the current customer.

Note, WC 1.4.2+ sets the **DONOTCACHEPAGE**, constant which means you can skip this step

May you use this **DONOTCACHEPAGE**, constant to identify woocommerce pages?
Why? because in germany the cart is "warenkorb", and "checkout" is "kasse"
https://www.santegra-international.com/warenkorb/ = cart

**Comment by Tobias-Conrad** [comment]
In germany we have two extra pages called "bestellung_bestaetigen__absenden/" 
and i habe bulk order page /schnellbestellung/ 
howto exclude this pages?

**Comment by Tobias-Conrad** [comment]
Did your fixes meet the needs of ameet3000 ind this post?
https://wordpress.org/support/topic/woocommerce-order-status-and-wp-ffpc

**Comment by Tobias-Conrad** [comment]
@petermolnar @gablau what about my thoughts above?

**Comment by petermolnar** [comment]
@Tobias-Conrad use the exclude URL regex field.
Settings -> WP-FFC -> Cache exceptions -> Don't cache following URL paths - use with caution!
http://regex101.com/ can help you build the regular expression.

This is a contribution and as stated in the support forum link, I'm not willing to support woocommerce myself.

**Comment by Tobias-Conrad** [comment]
for example: /cart/gix
Can you please give me a set of modifier like gix, i am new to regex.

**Comment by gablau** [comment]
some correction and explanation [#50](https://github.com/petermolnar/wp-ffpc/pull/50)

**Pull request merged**
