### PR TITLE
Some fix

### PR DESCRIPTION
**Pull request by gablau**
* woocommerce api endpoint exclusion
* small fix

### CODE REVIEW

**Comment by gablau** [comment]
@Tobias-Conrad
> 
May you use this DONOTCACHEPAGE, constant to identify woocommerce pages?

No (I try) the constant is set at run wordpress, the advanced-cache.php is before that so we need to be excluded by URL. 

> 
this i found on the wp fastest cache support place:
/wp-api/v1, /cart, /checkout, /receipt, /confirmation, /product

I do not think they are all correct, for example, I wish that our product pages are cached to speed up your site.
For other continue reading below...

This is the documentation of woocommerce endpoint for Checkout and Account
[https://docs.woothemes.com/document/woocommerce-endpoints-2-1/](https://docs.woothemes.com/document/woocommerce-endpoints-2-1/)

The base endpoint are: /my-account/ and /checkout/ 
The following endpoints are used for account-related functionality and are appended to the URL of the my-account page:

    View order – /view-order/{ORDER_ID}
    Edit account (and change password – /edit-account/
    Edit address – /edit-address/{ADDRESS_TYPE}
    Lost password – /lost-password/
    Logout – /customer-logout/

    example: /my-account/view-order/#76

The following endpoints are used for checkout-related functionality and are appended to the URL of the checkout page:

    Pay page – /order-pay/{ORDER_ID}
    Order received (thanks) – /order-received/
    Add payment method – /add-payment-method/
    
    example: /checkout/view-order/#76
    
That is correct excluded from this regex: ^/my-account/|^/checkout/
In the changes that I have proposed, the plugin searches the current values directly from woocommerce and correctly sets the regular expression, which is saved to wp-FFPC settings

For any modification of endpoints you have to re-save the settings of WP-FFPC !!!


Paypal IPN documentation
[https://developer.paypal.com/docs/classic/ipn/gs_IPN/](https://developer.paypal.com/docs/classic/ipn/gs_IPN/)
the IPN request is a POST request, is never cached, but the confirmation of validazine is a simple GET request, so we need to be excluded from the cache!

The url for IPN is like: http://yoursite.com/wc-api/CALLBACK/
    
Some problems for the old version: [https://github.com/woothemes/woocommerce/issues/5590](https://github.com/woothemes/woocommerce/issues/5590)

Official API documentation
[https://docs.woothemes.com/document/wc_api-the-woocommerce-api-callback/](https://docs.woothemes.com/document/wc_api-the-woocommerce-api-callback/)

Example API Url: 
http://yoursite.com/?wc-api=CALLBACK
http://yoursite.com/wc-api/CALLBACK/

so we need to exclude them with this regular expression: ^/wc-api|^/\?wc-api=

Please if anyone can do further testing for IPN I would be grateful

**Comment by Tobias-Conrad** [comment]
Thank you,
wellcome to your weekend! 
Can you please give an complete example what to exclude?
What to setup? Where to look?
so petermolnar can copy & paste it into his description.

**Comment by tommyredz91** [comment]
My WC account endpoints are not properly redirecting, so the customer won't either bè able to access and modify any of the input fields on the account page. I have got the AccessPress Mag free theme set-up on my site at: http://floodnews.net.
What on Earth am I supposed to do, to make it work properly once and for all?!?
Tell me how to fix this major issue once and for all, step by step, in detail!!

**Comment by petermolnar** [comment]
re @tommyredz91 
> Tell  me how to fix this major issue once and for all, step by step, in detail!!

Erm.. no?
This is a free plugin, supported as best I can, but:
a, I don't have time at the moment
b, I do not have to fix your issues.

Cheers.

**Comment by tommyredz91** [comment]
@petermolnar
Who the hell are you, to answer in such a rude way, asshole?

**Comment by petermolnar** [comment]
re @tommyredz91 

The author of the plugin?
I suggest you first learn to understand your own composing style before calling me names.

**Comment by tommyredz91** [comment]
@petermolnarIf you are the author of the plugin, you should learn how to treat your customers, geek!!

**Comment by peterbowey** [comment]
@tommyredz91 give @petermolnar some time. Generally, free plugins are a good community effort, and can benefit all with time. Appreciate the logic of doing some research and helping others - as Peter has.

**Comment by petermolnar** [comment]
@tommyredz91 
You're not my customer. You're not paying for it, and I owe you nothing at all. You are not entitled to demand anything.

This plugin was written for myself, to solve my own issues. The reason why I open source my software is that this is the way I'm contributing back to the community; this, on it's own does not mean I have to deal with requests at all. 

If you need this solved, pay someone to fix it for you. 
There are plenty of good WordPress programmers out there. 

I also recommend you to read a little on open source communities and to work on your behaviour; otherwise you'll quickly find yourself kicked out from places like this.

**Pull request merged**
