### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by tomcastleman**
It would be great if we could make this package composer deployable. I added a basic composer.json here, but also it would be good if your `wp-common` package is moved from a submodule to another plugin (or include them in this repo directly).

Thanks

### CODE REVIEW

**Comment by tomcastleman** [comment]
I know it's available via wpackagist, however that doesn't allow one to create and require development forks etc. Not only is making this composer friendly good practice but also it will enable me to contribute more easily :)

**Comment by petermolnar** [comment]
wp-common is a submodule for a reason; I do not want to move it to a separate plugin.

**Comment by tomcastleman** [comment]
OK. Well thanks for being so open to discussion and collaboration!

**Comment by petermolnar** [comment]
I did not want to sound offensive, sorry about that.

The wp-common is a small framework which would not make any sense on it's own and - in my opinion - cannot really be migrated to a plugin.

There is no dependency handling in WordPress apart from an alert to install another plugin so I do not think this would be a good idea.

However, the current wp-common folder do results in issues due to limitations in PHP itself. I'll try to think about it, but I'd rather copy-paste the abstract class instead of putting it into a separate plugin.

**Pull request merged**
